version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes: 
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks: 
      - onstrategy-mysql-docker
    ports:
      - "3308:3306"
  mysql2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes: 
      - mysql2-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks: 
      - onstrategy-mysql-docker
    ports:
      - "3310:3306"
  
volumes: 
  mysql-data: 
  mysql2-data:
networks: 
  onstrategy-mysql-docker: