version: '3.8'
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        PMA_HOSTS: onstrategy-mysql-docker.mysql,onstrategy-mysql-docker.mysql2 
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_ARBITRARY: 1
      ports:
        - "8999:80"
      networks: 
        - onstrategy-mysql-docker
volumes:
networks:
    onstrategy-mysql-docker: 
      external: true
