version: '3.8'
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        PMA_HOSTS: mysql,mysql2 
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_ARBITRARY: 1
      ports:
        - "8999:80"
      networks: 
        - onstrategy-mysql-docker
networks:
    onstrategy-mysql-docker:
      name:  onstrategy-mysql-docker 
      external: true
